spring:
  application:
    name: seminar
  profiles:
    active: dev

paths:
  /upload:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: The file to upload
      responses:
        '200':
          description: Successful upload